---
- name: Configuring standard CA certificates
  hosts: all
  become: yes

  tasks:
    # Installing ca-certificates package if the host is of Debian family
    - name: Installing ca-certificates package if the host is of Debian family
      package:
        name: ca-certificates
        state: present
      when: ansible_os_family == "Debian"

    # Installing ca-certificates package if the host is of RedHat family
    - name: Installing ca-certificates package if the host is of RedHat family
      package:
        name: ca-certificates
        state: present
      when: ansible_os_family == "RedHat"

    # Update CA certificate bundle on Debian
    - name: Update CA certificate bundle on Debian
      command: update-ca-certificates
      when: ansible_os_family == "Debian"

    # Update CA certificate bundle on RedHat
    - name: Update CA certificate bundle on RedHat
      command: update-ca-trust
      when: ansible_os_family == "RedHat"

---
- name: Validationg and installing Custom CA certificates
  hosts: all
  become: yes
  vars:
    ca_certificates:
      - name: "CA1"
        cert_src: "./CA1.crt"
        key_src: "./CA1.key"
        cert_dest_debian: "/usr/local/share/ca-certificates/CA1.crt"
        cert_dest_redhat: "/etc/pki/ca-trust/source/anchors/CA1.crt"
        key_dest: "/etc/ssl/private/CA1.key"
      - name: "CA2"
        cert_src: "./CA2.crt"
        key_src: "./CA2.key"
        cert_dest_debian: "/usr/local/share/ca-certificates/CA2.crt"
        cert_dest_redhat: "/etc/pki/ca-trust/source/anchors/CA2.crt"
        key_dest: "/etc/ssl/private/CA2.key"
      - name: "CA3"
        cert_src: "./CA3.crt"
        key_src: "./CA3.key"
        cert_dest_debian: "/usr/local/share/ca-certificates/CA3.crt"
        cert_dest_redhat: "/etc/pki/ca-trust/source/anchors/CA3.crt"
        key_dest: "/etc/ssl/private/CA3.key"
  tasks:
    - name: Validate and copy CA certificates and keys
      block:
        - name: Validate {{ item.name }} certificate
          stat:
            path: "{{ item.cert_src }}"
          register: cert_check

        - name: Check {{ item.name }} certificate validity
          shell: "openssl x509 -checkend 0 -noout -in {{ item.cert_src }}"
          when: cert_check.stat.exists

        - name: Copy {{ item.name }} certificate to the host
          copy:
            src: "{{ item.cert_src }}"
            dest: "{{ item.cert_dest_debian }}"
          when: 
            - cert_check.stat.exists
            - ansible_os_family == "Debian"
          notify: update_ca_certificates (Debian)
        - name: Copy {{ item.name }} certificate to the host
          copy:
            src: "{{ item.cert_src }}"
            dest: "{{ item.cert_dest_redhat }}"
          when: 
            - cert_check.stat.exists
            - ansible_os_family == "RedHat"
          notify: update_ca_certificates (RedHat)

        - name: Copy {{ item.name }} key to the host
          copy:
            src: "{{ item.key_src }}"
            dest: "{{ item.key_dest }}"
            mode: "0600"
          when: cert_check.stat.exists
      loop: "{{ ca_certificates }}"
  handlers:
    - name: Update CA certificates (Debian)
      command: "update-ca-certificates"
      listen: update_ca_certificates
      when: ansible_os_family == "Debian"

    - name: Update CA certificates (RedHat)
      command: "update-ca-trust"
      listen: update_ca_certificates
      when: ansible_os_family == "RedHat"  

---
- name: Deploying a python application into a virtual environment
  hosts: all
  become: yes
  
  vars:
    deployment_location: /opt/example
    application_port: 5000
    wheel_file: example-1.1.1-py3-none-any.whl

  tasks:
    # Ensure deployment directory exists
    - name: Ensure deployment directory exists
      file:
        path: "{{ deployment_location }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: '0755'

    # Install Python 3 and pip
    - name: Install Python 3 and pip
      package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv

    